pipeline {
    agent any

    stages {
        stage('Run backend unit tests') {
            steps {
                dir('bugtracker-backend') {
                    go test -v ./...
                }
            }
        }
    }
}