pipeline {
    agent any

    stages {
        stage('Run backend unit tests') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root -v /var/jenkins_home/go-cache:/.cache/go-build -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                   sh 'go test -v ./...'
                }
            }
        }

        stage('Run frontend unit tests') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '-v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}